apiVersion: apps/v1
kind: Deployment
metadata:
  name: lunch-learn
spec:
  selector:
    matchLabels:
      app: metrics
      department: engineering
  replicas: 3 
  template:
    metadata:
      labels:
        run: lunch-learn
        app: metrics
        department: engineering
    spec:
      containers:
      - name: lunch-learn
        image: "lekhnath12/demo:latest"
        ports:
        - containerPort: 7777
